# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.synced_folder "src", "/host/src"
  config.vm.synced_folder "output", "/host/output"
end
