#!/bin/sh

bspc config border_width 2
bspc config top_padding $BAR_HEIGHT
bspc config window_gap 20


bspc config split_ratio         0.52
bspc config single_monocle      true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

if [ "$(xrandr | grep ' connected' | wc -l)" -gt 1 ]; then
  bspc monitor "eDP1" -d I II III IV V
  bspc monitor "DP2" -d I II III IV V
else
  bspc monitor "eDP1" -d I II III IV V VI VII VIII IV X Dump
  bspc monitor "DP2" -d None
fi

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a scratchpad --sticky
bspc rule -a URxvt:URxvtQuake state=floating stick=on border=off

# Set background
feh --bg-scale $BACKGROUND_IMAGE
# Start bar
# killall panel ; $SCRIPTS/panel/panel &
killall panel.py ; $SCRIPTS/panel/panel.py & 

