[[filter]]
label = "edu"
archive = true
query = "to:connectionists"

[[filter]]
archive = true
queryOr = [
  "(from:linkedin.com)",
  "(from:vercel[bot])"
]

[[filter]]
label = "gbp"
archive = true
queryOr = [
  "from:support@tesco.com",
  "from:no-reply@digitalocean.com",
  "from:no-reply-aws@amazon.com",
]

[[filter]]
label = "prp"
queryOr = [
  "from:banardmarcus.co.uk",
  "from:laurels.co.uk",
  "from:haart.co.uk",
  "from:e.rightmove.co.uk",
]

[[filter]]
label = "blg"
queryOr = [
  "from:wordpress.com",
  "from:drawinglinks@substack.com",
]
