#!/bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

lefts=('workspaces.sh' 'title.sh')
rights=('volume.py' 'memory.py' 'cpu.py' 'battery.py' 'pacman.py' 'clock.sh')

i=0
for script in ${lefts[@]}; do
  $PANEL_PATH/widgets/$script | $PANEL_PATH/labeler.sh l"$i" > "$PANEL_FIFO" &
  i=$((i+1))
done

i=0
for script in ${rights[@]}; do
  $PANEL_PATH/widgets/$script | $PANEL_PATH/labeler.sh r"$i" > "$PANEL_FIFO" &
  i=$((i+1))
done

. $PANEL_PATH/panel_colors

cat "$PANEL_FIFO" | \
  $PANEL_PATH/panel-parser.py | \
  tee $PANEL_PATH/.panel-parser.log | \
  lemonbar \
    -g x"$BAR_HEIGHT" \
    -f "$MAIN_FONT" \
    -f "FontAwesome"
    -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
