#!/usr/bin/env python

from subprocess import Popen, PIPE

process = Popen(["bspc", "wm", "--get-status"], stdout=PIPE)
(status_string, error) = process.communicate()

statuses = {}

for segment in status_string.decode().split(":"):
    # Make sure segment is size two
    if len(segment) != 2:
        continue

    # Make sure segment has a number
    try:
        int(segment[1:])
    except ValueError:
        continue


    # Store workspace status in a dictionary
    workspace_number = int(segment[1:])

    workspace_status = segment[0]

    statuses[workspace_number] = workspace_status

# Change into a grid
grid_string = ""

grid_string += "\u2554\u2550\u2550\u2550\u2566\u2550\u2550\u2550\u2566\u2550\u2550\u2550\u2557\n"
for y in range(2):
    if y != 0:
        grid_string += "\u2560\u2550\u2550\u2550\u256C\u2550\u2550\u2550\u256C\u2550\u2550\u2550\u2563\n"

    grid_string += "\u2551"

    for x in range(3):
        index = (y * 3) + x + 1
        
        grid_string += " " + statuses[index] + " "
        grid_string += "\u2551"

    grid_string += "\n"

grid_string += "\u255A\u2550\u2550\u2550\u2569\u2550\u2550\u2550\u2569\u2550\u2550\u2550\u255D\n"

print(grid_string)

